# Generated by Django 4.2.7 on 2023-11-09 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djstore", "0002_products_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="product_id",
            new_name="product",
        ),
    ]
