# Generated by Django 4.2.7 on 2023-11-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djstore", "0003_rename_product_id_cart_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="photo",
            field=models.ImageField(null=True, upload_to="photos/"),
        ),
    ]
