# Generated by Django 4.2.7 on 2023-11-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djstore", "0004_products_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["id"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="products",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
